name: check/lint

on: ["push"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
      - name: Set up Python
        uses: actions/setup-python@v5.1.1 
        with:
          python-version: "3.12.3"
      
      - name: Install Rye
        uses: eifinger/setup-rye@v4.2.1
        with: 
          version: 'latest'
          enable-cache: true
          cache-prefix: 'hksc_disassembler'
      
      - name: Run Rye
        run: |
         rye sync --all-features
         rye run lint
         rye test